### ISSUE TITLE
luarocks

### ISSUE THREAD

**Issue by kazuminn** [ie-developers/ie-questions#11]
mac os x yosemite 10.10

lua 5.1.5をbrew (version0.9.5)でinstallして

このバージョンに対するluarocksをbrew install したいのですが、for5.2をダウンロードしてしまいます。

for5.1をダウンロードしたいのですが、どうすれば良いのでしょうか

**Comment by Code-Hex** [comment]
これでいけそう...

$ brew tap homebrew/boneyard

$ brew versions luarocks

ここ参考にしてみて
http://qiita.com/ryam/items/066818fd149e68a98797

**Comment by kazuminn** [comment]
できました。
ありがとうございます。
