### ISSUE TITLE
vim本体のバージョン管理

### ISSUE THREAD

**Issue by kazuminn** [ie-developers/ie-questions#12]
質問というか、vimのバージョン管理って皆さんどうしてるかなーと思って投げました。
(HomeBrew 0.9.5 ,mac  yosemite 10.10)

私は今まで
　　brewでvimを管理して、luaも管理してましたが、(vimは、if_lua関連で/usr/local/lib/にバイナリファイル"liblua.5.2.dylib"が必要。)
今
　　**env_formulaをanyenv以降しまして、それだとlua for 5.2はバイナリ　
　　を~/.anyenv/envs/luaenv/versions/5.2.1/bin/luaに探しに行きます。

brewのluaは、コンフリクトするとダメなのでuninstallしました。

して、vimを起動

すると、vimはluaのバイナリが無いと激おこして起動しません。

改善方法として、シンボリックリンクしたりして今のバイナリを見てもらえばいいと思いますが、

もともと、brewなvimってformulaのバージョン低いですし。
vimをbrew管理から移行したいなーと

皆さん、どう管理してますかー？
(一応,vimにパッチを当てて自分だけのvimを作りたいと思っています。)

**Comment by atton** [comment]
私は独自パッチ無しの HEAD 使ってますね。
有効な interp は
- ruby (rbenv)
- python (system default)
- lua (brew)

ですかね。
なので

`brew install --with-lua --HEAD vim`

くらいでやってます。
独自パッチ入れたいのなら `brew edit vim` くらいして patch をあてると楽な気も。

**Comment by kazuminn** [comment]
@atton- 

brew edit で既存のものをCustomizeできるのですね。知らなかったです。
つまり、 最新のものにできると。
luaも今は触らないので、brew に戻してみようかなーと思います。

ありがとうございます。
