### ISSUE TITLE
OSI基本参照モデル

### ISSUE THREAD

**Issue by kazuminn** [ie-developers/ie-questions#13]
ネットワーク環境 wimaxルータ。

　OSI基本参照モデルは、
国際標準化機構 (ISO) によって制定された、異機種間のデータ通信を実現するためのネットワーク構造の設計方針「開放型システム間相互接続 (Open Systems Interconnection、OSI)」に基づいて通信機能を7階層（レイヤ）に分割した規格である。
　7層から1層までパケットがカプセル化され、運搬されるとのことですが、
どの層がどの機器に対応してるのですか？

**Comment by atton** [comment]
その辺りは情報ネットワークIでやる範囲ですねー。
層と対応する機器名は
- 4-7層 ゲートウェイ
- 3層 ルータ
- 2層 スイッチ
- 1層 リピータ

とかです。
4-7 層はやりたいことによって機器とかの名前が違う(IDS とかファイヤウォールとか)のと、リピータは今はほとんど使われないので
- 3層 ルータ
- 2層 スイッチ

だけ覚えたら良いですかねー。

ちなみに Wimax だと IP レベルの機器なので3層ですね。

参考 ： [初級シスアド講座 ネットワーク(リピーター,ブリッジ,ルーター,ゲートウエイ)](http://www.pursue.ne.jp/jouhousyo/sysad/Network/Interface.html)

**Comment by kazuminn** [comment]
お。よくわかりました。ありがとうございます。
