### ISSUE TITLE
eachメソッドの先にnilがある。

### ISSUE THREAD

**Issue by kazuminn** [ie-developers/ie-questions#14]
ruby 2.1.5 
mac ox 10.10

https://github.com/kazuminn/twitter_/blob/master/kusoripu.rb
（コンセプトはreadme見てください。)
こちらのコード16行目の配列でnilが入ってると、その先の
n_reply_to_screen_nameメソッドはレシーバーがnilだとエラーが起きちゃうわけです。
compact!メソッドをeachの前に入れても、破壊されたものがNillclassのものなので
eachはダメだと怒られちゃいます。

どうすればよいでしょうか。

**Comment by atton** [comment]
えーっと。ちょっと整理したいのだけれど
配列に nil が入ることがあるので compact したい、ってのはokです。

> compact!メソッドをeachの前に入れても、破壊されたものがNillclassのものなので

ってのが良く分からないです。
どういう風に実行した時に何が起きて何がダメかちょっとまとめてみましょう
(あと、このコードそのままじゃ動かない気もします……)

**Comment by atton** [comment]
あとエスパーすると nil な時にまずいのは `x.in_reply_to_screen_name` な気がする。
こんな感じ?

``` ruby
client = Twitter::REST::Client.new do |config|
  config.consumer_key = "fQDpM4Hf9W3c6n3X5heJwLZ74"
  config.consumer_secret = "wlx82Y2zLx0PvAnW6OTjVNBWa2uJjlwysHgCa70iFq8NG0MSNx"
  config.access_token = "2416079641-KZuLIT277rtE1EoNQoq6HcC65wcyAMGkt7f4QOe"
  config.access_token_secret = "BG4FSx2iXMztvwYQ8GAm9j2qfSBtHQBAfVFcYOl0cfB3V"
end

hash = {}
client.user_timeline("warugaki_kazumi").each do |x|
  screen_name = x.in_reply_to_screen_name
  unless screen_name.nil?
    unless hash.has_key?(screen_name) then
      hash[x.in_reply_to_screen_name] = 1
    else
      hash[x.in_reply_to_screen_name] = 2
    end
  end
end

hash.each do |key,value|
  if value.to_i == 1
    client.update("@warugaki_kazumiは、" + key + "さんにクソリプをしている可能性があります。")
  end
end

```

**Comment by atton** [comment]
あと細かいところ
- ruby のインデントはタブ2つ
- require 'rubygems' は無くても良い(1.8 くらいまでは必須)
- twitter の token は公開しない方が良い
- 意味のある名前を使う (`hash = {}` だと何のハッシュだか分からない)
- Class に分けてるのは何故なのだろう(というか動かなさそうに見える。取ると動く)

**Comment by kazuminn** [comment]
- tokenは、更新ができたと思うので更新しておきます。
- Classに分けている意味はないです。(コード群は、オブジェクト指向設計にするためにClassで括るものだと思っています。
- nilな問題は、もう少し整理してみます。

**Comment by hanachin** [comment]
@atton- `consumer_secret`と`access_token_secret`ベタ書きで貼るのは不味いのでは

**Comment by hanachin** [comment]
エスパーすると

``` ruby
client.user_timeline("warugaki_kazumi") # => nil
```

のときに`each`を呼ぶと

``` ruby
client.user_timeline("warugaki_kazumi").each do # nil.eachしてるのでエラー
```

みたいな感じですか?

**Comment by kazuminn** [comment]
@atton-  さん @hanachin 　さん
tokenの件は、regenerateしたので大丈夫です。

**Comment by kazuminn** [comment]
事の発端は、

```
client.user_timeline("warugaki_kazumi").each do
```

だと、 x.in_reply_to_screen_nameがxがnilの時エラー

で、nilを消そうとcompact!

```
client.user_timeline("warugaki_kazumi").compact!.each do
```

ってすると、compact!によって破壊されたものはNilクラスのインスタンスなので、
eachメソッドを使うとエラーがでるよー。で

破壊しないようにcompact

```
client.user_timeline("warugaki_kazumi").compact.each do
```

　だが、

```
kusoripu.rb:15:in `block in <main>': can't convert Twitter::NullObject to Integer (Twitter::NullObject#to_int gives Twitter::NullObject) (TypeError)
```

と激おこ。

nil消したはずなのに「あれー？」って感じですね。

**Comment by kazuminn** [comment]
細かいことを付け足すと

```
client.user_timeline("warugaki_kazumi").each do # nil.eachしてるのでエラー
```

ってのは、厳密にはnill.eachしてないので、エラーにならないのでは。

```
client.user_timeline("warugaki_kazumi").compact!.class #Nillクラス
```

これ、compact!で破壊されたものはNillクラスのインスタンスなんですね。

**Comment by hanachin** [comment]
`compact`と`compact!`は動作が違いますね。`compact!`で何も変更がなかった場合`nil`が返ります

> compact は自身から nil を取り除いた配列を生成して返します。 compact! は自身から破壊的に nil を取り除き、変更が 行われた場合は self を、そうでなければ nil を返します。
> http://docs.ruby-lang.org/ja/2.2.0/method/Array/i/compact.html

**Comment by kazuminn** [comment]
@hanachin さん
　　なるほどです。
　　compactを使えばいいのですね。

でも

```
kusoripu.rb:15:in `block in <main>': can't convert Twitter::NullObject to Integer (Twitter::NullObject#to_int gives Twitter::NullObject) (TypeError
```

と怒られます。

**Comment by atton** [comment]
compact は  `client.user_timeline("warugaki_kazumi")` の中身に nil がある時に消します。

今回 nil なのは `client.user_timeline("warugaki_kazumi")` の中身の tweet の `in_reply_to_screen_name` なので、 each に失敗してるんじゃなくて hash への代入に失敗してますね

**Comment by kazuminn** [comment]
https://gist.github.com/atton-/ea9178765cf4fcdfcc83

https://twitter.com/_atton/status/578177683873349632

```
hash で返るものには to_int が必要
```

ってhash methodの戻り値のオブジェクトにはto_intなinstance methodを持っていなければならない
って解釈でいいです？

**Comment by atton** [comment]
> ってhash methodの戻り値のオブジェクトにはto_intなinstance methodを持っていなければならない
> って解釈でいいです？

その解釈であってます。
ちなみにこれが原因でどのようなことが起こってるか説明できます?

**Comment by kazuminn** [comment]
to_int methodを持っていないから、hashインスタンスのkeyにできない事案が起こっている。

ですかね？

**Comment by atton** [comment]
だいたいあってます。
key にしようとして to_int が存在していないものは何です?

**Comment by kazuminn** [comment]
HasHashMethod.new　オブジェクトですよね。

**Comment by atton** [comment]
あーっと。私の gist じゃなくて君のコードの方ね。

**Comment by kazuminn** [comment]
あ。x.in_reply_to_screen_nameの戻り値。ですかね。

**Comment by atton** [comment]
そうそう正解。

だから、

> kusoripu.rb:15:in `block in <main>': can't convert Twitter::NullObject to Integer (Twitter::NullObject#to_int gives Twitter::NullObject) (TypeError

のエラーは each とか compact が問題ではなくて、  `x.in_reply_to_screen_name` の object を hash の key にしてるのが問題、というお話でした

**Comment by kazuminn** [comment]
あ、なるほどです。

hashではなくて他のものにすれば、動きそうですね。

よくわかりました。ありがとうございました。
