### ISSUE TITLE
vim plugin

### ISSUE THREAD

**Issue by kazuminn** [ie-developers/ie-questions#15]
# summary
- 下記の問題を解決するpluginないですか？
# the present situation
- twitter api読んでる
# question

ファイル間の単語検索に骨が折れる。

**Comment by atton** [comment]
え、えーっと。下記の問題と言われてもほとんど状況が分からないので答えられないです。

Twitter API 読んでるのは良いんですけれど、何で Vim Plugin が関係してるのか分からないです。
Vim で直接 Twitter API の リファレンスの web ページを w3m.vim で読んでるのか、 Twitter の gem を読んでるのか。
質問する時は今何で何をしてて、何が問題なのかとか、状況を説明しましょう。

**Comment by kazuminn** [comment]
目的はAPIはどのようにできているのか見いてみようかと思いまして。

ローカルにtwitterのgemをgit cloneしていて、
例えば,
b.rbでdef hogeされているのですが
それが使われている場所を探すのを
vim pluginが補助してくれるかと。

**Comment by atton** [comment]
そういった用途なら ctags とか global とかで調べましょう

**Comment by kazuminn** [comment]
おー！ありがとうございます。
