### ISSUE TITLE
pyenv

### ISSUE THREAD

**Issue by kazuminn** [ie-developers/ie-questions#16]
mac 10.10
brew 0.9.5

```
brew instsall pyenv 
pyenv install 3.4.2
pyenv global 3.4.2
pyenv rehash
```

をして
zshrcに

```
#plenv
if which pyenv >& /dev/null; then
        eval "$(plenv init -zsh)";
fi

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
```

として

```
source .zshrc
which -a python
/usr/bin/python/
```

でsystemのpythonしかない状態なのですが、

どうすればいいですか？

**Comment by cota2n** [comment]
[pyenv#Homebrew on Mac OS X](https://github.com/yyuu/pyenv#homebrew-on-mac-os-x)
brewでインストールしたなら`eval "$(pyenv init - zsh)"`を追加するだけでいいので

```
#pyenv
if which pyenv >& /dev/null; then
        eval "$(pyenv init -zsh)";
fi
```

そもそも `plenv init` になってますね。:stuck_out_tongue:
直してターミナル再起動後にpythonの参照先が変わっていなければ

```
pyenv global 3.4.2
pyenv rehash
```

しなおしてみて下さい。

**Comment by kazuminn** [comment]
あ、pytoが原因でした。お恥ずかしい。

@cota2n さんありがとうございました。
