### ISSUE TITLE
Centos7 keymapping

### ISSUE THREAD

**Issue by kazuminn** [ie-developers/ie-questions#18]
環境
- Centos7 CUI 最小構成
- Aキーの横にcapsキーがある。

<h3>windowsキーボードのcapsをctrlキーにしたいです。</h3>

下記の方法を試みましたが、できませんでした。
他に方法はないでしょうか？
# xmodmap
- $ unable to open display
- (X window systemがないのが原因なので入れましたが、
- Xコマンドを打つと画面が真っ暗になるのでできない)
# setxkbmap
- cannot open display "default display"
- 上と一緒
# gsettings
- Gnomeじゃないので、使用できない。

**Comment by atton** [comment]
えーっと。 物理マシン + 物理日本語キーボード環境、って想定で良いのですかね?
その場合だと最小構成なので X 使う方法じゃ無理そうです。
参考になりそうなのは以下とか?
- https://wiki.archlinux.org/index.php/Extra_keyboard_keys_in_console
- http://www.noah.org/wiki/CapsLock_Remap_Howto#Linux_script
- http://qiita.com/muniere/items/74b0df930c6830a263b0

とりあえずやったこと無いのでくわしくは分かんないですねー

**Comment by kazuminn** [comment]
妥協して
Gnome Desktop入れちゃいました。

ありがとうございました。
