### ISSUE TITLE
gemでvimgolfなコマンドが入らない件

### ISSUE THREAD

**Issue by kazuminn** [ie-developers/ie-questions#2]
http://vimgolf.com/
上記のvimfolfをするために、下記のコマンドを実行しました。

%gem install vimgol
%vimgolf setup

しかし、
zsh: command not found: vimgolf
だと

shimsディレクトリーを見ましたが、vimgolfなコマンドがないです。
解決方法がしりたいです。

**Comment by atton** [comment]
コマンドが入らない場合は
- 実行したコマンド
- 実行している環境(OSのバージョン, Ruby とかのバージョン)
- 実行したログ

などを書くようにしましょう。
URLだけだと何も分からないです……

**Comment by atton** [comment]
ちなみに
- rbenv 0.4.0
- ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin13.0]

では

`gem install vimgolf` で `vimgolf (0.4.6)` が入ったのを確認しました

**Comment by hanachin** [comment]
@kazuminn description更新してもGitHubの通知こないので気づきません。
「descriptionを更新しました」みたいなコメント入れるといいと思います

`rbenv exec vimgolf`はいかがですか〜

`shims`にないのは`rbenv rehash`してないのが原因かも。
`rbenv rehash`してから`shims`確認してみてください。

`rbenv-gem-rehash`使うと、`gem install`したとき自動で`rbenv rehash`してくれて便利です。
https://github.com/sstephenson/rbenv-gem-rehash

**Comment by hanachin** [comment]
:thought_balloon: @atton- ie-developersじゃないけど横やりいれてしまいました

**Comment by atton** [comment]
@hanachin いえいえありがとうございますー
むしろ指摘が来るのはウェルカムです。
そのために公開してる感もあるのでー

**Comment by atton** [comment]
@kazuminn どんな感じです? 問題解決しましたー?

**Comment by kazuminn** [comment]
@atton-  @hanachin  rbenv rehashが原因で、解決しました。

**Comment by atton** [comment]
@kazuminn おっけーです。解決したら issue を close してもらえるとうれしいです

**Comment by kazuminn** [comment]
@atton- 了解です。ありがとうございました。
