### ISSUE TITLE
Vim Script

### ISSUE THREAD

**Issue by kazuminn** [ie-developers/ie-questions#20]
環境
- os x yosemite
- vim 7.4

本題

<pre>
let hoge = "何か"
%s/piyo/hoge/g
</pre>

とかして
置換後の文字列を変数にしてhogeを展開したいのですが。
何か方法ありますでしょうか？

**Comment by rbtnn** [comment]
グローバル変数でhogeを宣言しておいて、

> %s/piyo/\=g:hoge/g

とすればできると思います。

**Comment by rbtnn** [comment]
もし、そのバッファ内でしか使用しないのであれば、グローバル変数`g:hoge`ではなくバッファ変数`b:hoge`のほうが無難。

> let b:hoge = "何か"
>  %s/piyo/\=b:hoge/g

**Comment by kazuminn** [comment]
できましたー。
バッファ内なのでb:でやります。

ありがとうございました。
