### ISSUE TITLE
Django

### ISSUE THREAD

**Issue by kazuminn** [ie-developers/ie-questions#21]
こんにちは、
今Djangoでwebアプリケーションを組んでいます。

python 2.7
Django 1.4

今カート機能を実装しています。

カートに挿入するために、「カートに追加」ボタンを押せば購入できます。
現段階の実装では、カート番号をurlにはめ込んで画面推移を行っています。
ex

<pre>
https://hoge/hoge/カート番号
</pre>

これだと、推移後にカート番号をデータベース検索するので脆弱性が出現するかもしれません。
csrf_tokenってのがあるのですが、これで大丈夫ですかねー。

「railsとかでも、こんなのあるんだけど」とかでもお願いします。

**Comment by hanachin** [comment]
[安全なウェブサイトの作り方：IPA 独立行政法人 情報処理推進機構](https://www.ipa.go.jp/security/vuln/websecurity.html)

**Comment by kazuminn** [comment]
お。頑張ってみてみます。

Thank you:D
