### ISSUE TITLE
evalではまった。

### ISSUE THREAD

**Issue by kazuminn** [ie-developers/ie-questions#24]
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
os x yosemite

動的にhoge、piyo変数を宣言してそれを配列にしたかったが
配列後のeachができなくてハマっています.
なぜなら、下記の#####の部分がが自分の知識では動的にhoge,piyoと書けないから

<pre>
["hoge","piyo"].each do |x|
  plus = "@" + x
  eval('#{plus} = [1,1,1,1,1]')

  #####.each do |i|
    print i + i
  end
end
</pre>

動的に#####をhoge,piyoにしたいのですが、どうすればよろしいでしょうか？

**Comment by kazuminn** [comment]
issue書きましたー

**Comment by hanachin** [comment]
> eval('#{plus} = [1,1,1,1,1]')

`''`の中では式展開されません

``` rb
eval("#{plus} = [1,1,1,1,1]")
```

**Comment by kazuminn** [comment]
なるほど。
" "にしたのですが

#####の部分の書き方がわかんないです。><

**Comment by hanachin** [comment]
``` rb
# えばる
eval(plus).each do |i|
  print i + i
end

# インスタンス変数にいれてるなら`instance_variable_get`で取れる
instance_variable_get(plus).each do |i|
  print i + i
end
```

**Comment by kazuminn** [comment]
なるほど。なるほd。
問題は、解決しました。^^

回答、ありがとうございました。
