### ISSUE TITLE
Haskell 勉強会調整

### ISSUE THREAD

**Issue by atton** [ie-developers/ie-questions#6]
#5 で @maeken2010 さんからHaskell 勉強会しましょうー、って要望があったのでその調整とか

**Comment by atton** [comment]
どんな感じのやつやりましょう? 私から思う提案としては
- maeken さんが分かんないやつの解説とかそーいうやつ
- なんか本読む
- なんかWeb読む

とか? あとは日程とかですかねー。

**Comment by maeken2010** [comment]
自分は高階関数や型クラス，Functorの復習しつつモノイド，Monad辺りをやりたいです．
できればH本に無い内容(FreeMonadとか圏論とか)にも突っ込めたら嬉しいなーと．

日時は金曜日土曜日以外であれば基本的に大丈夫です．極力あっとんさんや皆さんに合わせたいです．

**Comment by kazuminn** [comment]
私は、勉強会参加したいなーと思います。
Haskellの入門の入門も触ったことがありません。
上の人たちは、かなりやってると思いますので、提案として
- 結構やってるよーって人たちと、これからーって人たちは分ける方向がいいかと
- すごいH本気になっていまーす。

日程は、土日は基本フリーでーす。

**Comment by atton** [comment]
今のところ希望者は2名? 他の人もいたりするのかな。

@maeken2010 さんはやりたい内容は具体的にあります?(このページとかこのWebが読みたいとか)
@kazuminn さんはすごいH本気になってるっぽいのですごいH本にしましょうかねー

**Comment by atton** [comment]
とりあえず今月中は私ちょっと動けない感あるので、日程調整と内容の調整とかは @maeken2010 さんにお願いします。

ちなみに私は基本的に 火曜 - 金曜 がアウトかな。

**Comment by maeken2010** [comment]
Monadとか型とかを理論な所から理解したいとは思っています．具体的な本とかはもう少し考えておきます…

日程は来月の日曜日辺りになるかもですね．細かい勉強会の内容は他に参加する人と話しながら決めていきたいと思います．

**Comment by maeken2010** [comment]
結構Haskellやってみたい人が多いみたいなので，内容は一応Haskell勉強会ということでhaskell触ってみようぜ，というスタンスでやってみようと思います．

日程は11/30Sunにしようと思います．時間は9:00〜夕方頃まで．

H本で言うイントロ~mapまで頑張って進めたらいいな…という感じです．質問は基本的に自分が受け付けていきます．折角なのでAtcoderやProject Eulerの問題からいくつか解く，というのもやってみたいです．

自分が個人的にわからないとこは合間合間にattonさんに聞いていきます．型システムだとか．

**Comment by atton** [comment]
日程、 [Oculus Game Jam](http://ie.u-ryukyu.ac.jp/news-ie/2014/10/07/oculus-gamejam-%E9%96%8B%E5%82%AC%E3%81%97%E3%81%BE%E3%81%99/) と被りそうだけれどokです?

**Comment by maeken2010** [comment]
ごめんなさい失念してました…orz

1つ前の11/23Sun-11/24Monはどうでしょう．24は振替休日ですし．
23では上記の通りに行って，24ではもっとやりたい人向けにもう少し突っ込んだやつやったりとか．
24の内容は様子見ながら，~IOぐらいまでを目標に．

**Comment by atton** [comment]
了解です。
23,24 私は今のところおっけーです。

**Comment by kazuminn** [comment]
私も今の所おkです。

**Comment by maeken2010** [comment]
何度もすみません！
24は321でOculusな勉強会があるらしいので，少し変更してhaskell勉強会は23日のみ，ということでよろしくお願いします！

**Comment by maeken2010** [comment]
若干途中ですが一応資料作ってみました．H本で言う1章〜4章です．ご確認下さい．
http://ie.u-ryukyu.ac.jp/~e135732/pdf/Haskell%E5%8B%89%E5%BC%B7%E4%BC%9A1.pdf

当日はもう１つの資料としてこちらのサイト様 http://capm-network.com/?tag=Haskell も使っていこうと思います．

**Comment by atton** [comment]
おっけーです。資料にコメントとかいります?
ここで言うか直接言うかどちらかですかねー? 今日の午後とかはいそうなのでGithubか直接声かけてもらえれば。

あと開始時間とか場所とか人数とかどうなってますかねー

**Comment by maeken2010** [comment]
午後〜明日ぐらいはバイトで動けないのでここに書いてもらえると嬉しいです．

時間，場所は予定通り23日9時から321で行います．
atnd作成してました．表明してるのは今のところ11人で，もう少し増えそうな予感がします．https://atnd.org/events/59089

**Comment by atton** [comment]
おっけーです。
- 気になったとこ(だいぶ気になる)
  - 「関数型」の定義ってどこ参考にしてます?
- 気になったとこ(口頭で言うかもしれないし若干スライドだけじゃ分かんないかもくらい)
  - 「実行すると必ず同じ結果を得られる」だと誤解を招きそうなレベルですごいように聞こえないかな。条件とか制約とか言いたいよね。どういう時に何が同じ結果?
  - 「インデントを見るので」って性質はオフサイドルールって言うらしいです
  - リストの説明で「同じ要素の集まり」って [1,1,1,1] とかに誤解されないかな
  - タプル「違う種類もok」種類とかって型をぼかして言う方が良いのかな。型って言うとまずい?
  - 「型は必ず大文字から」の後にTrueあるの大丈夫かな。あれってなして大文字なのかとかね。
  - パターンマッチで「引数の構造」って書いてるとこと、引数の構造って説明無しだと構造ってなんだろうしそう
  - where 節「違うパターン」ってなんだろ。
  - 遅延評価の話ってしなくても大丈夫かな

**Comment by atton** [comment]
なんか大分いろいろ書き換えちゃったけれどざっくりこんな感じかなー。
あとATND参加登録しておきましたー。おそらく09:00にはこないので先にやっておいてもらえると。

**Comment by atton** [comment]
なんか23日は全部任せちゃってる感ありますね。
24日どうしようか的な話があった気もするけれどどうなってるでしょう。
マエケンさん何かしたいとか希望あります?

**Comment by maeken2010** [comment]
ありがとうございます！
自分も見なおしてだいぶ気になったので下記訂正します．

> 「関数型」の定義ってどこ参考にしてます?

[wikipediaの記事](http://ja.wikipedia.org/wiki/%E9%96%A2%E6%95%B0%E5%9E%8B%E8%A8%80%E8%AA%9E) とH本を参考にしました．
- ここでの「関数」とは、数学でいう「関数」であり、手続き型プログラミングなどにおける「関数」ではないことをまず注意する
- 複雑なコンピュータプログラムに相当する関数を作るために、第一級関数を扱えることなどが関数型言語には必要である。
- 純粋関数型プログラミングは違います。コンピュータに何をするかは伝えま せん。何であるかを伝えるのです。

「1.「何であるか」をコンピュータに伝える」 は別に関数型の特徴とかでは無いし(純粋関数型の特徴？)，「2.高階関数」じゃなくて第一級関数が正しいですね．

> 遅延評価の話ってしなくても大丈夫かな

レンジの話で取り上げようと思ってました(take 10 [1..]とか)．関数呼び出しも遅延されること等も書いたほうが良いですね．

> 「実行すると必ず同じ結果を得られる」だと誤解を招きそうなレベルですごいように聞こえないかな。条件とか制約とか言いたいよね。どういう時に何が同じ結果?

ちょっとここ答えられないです…「再代入できる変数が無い」という制約の元で「同じ引数を与えれば返り値が必ず同じ結果」になる，で合ってますでしょうか…．
すごいように聞こえると言えばIOな処理も実は〜みたいに紹介するべきですかね．

> リストの説明で「同じ要素の集まり」って [1,1,1,1] とかに誤解されないかな
> タプル「違う種類もok」種類とかって型をぼかして言う方が良いのかな。型って言うとまずい?

あえて型って言うのを避けて要素とか種類とか書いてました．「型とはなんぞや」みたいな話になってしまいそうで…

> 「型は必ず大文字から」の後にTrueあるの大丈夫かな。あれってなして大文字なのかとかね。

正確には「型と値コンストラクタ」が大文字ですね…値コンストラクタだとあれなので「型が取りうる値の種類」とかですかね．

> パターンマッチで「引数の構造」って書いてるとこと、引数の構造って説明無しだと構造ってなんだろうしそう

いくつか例を出して説明するつもりでした．([]とx:[]とx:xsと〜等)

> where 節「違うパターン」ってなんだろ。

例えば

```
hoge [] = "hoge"
hoge xs = "hogepiyo"
```

とあったら[]のパターンとxsのパターン，という具合です．

**Comment by maeken2010** [comment]
24日は折角なのでよろしかったら何かやりたい感はあります．昼〜夕方だと自由に動けます．
型システムやモナドや圏論やラムダ計算やカリーハワード対応や最近は再帰とか色々興味ありますがまずは「型とは」って話がしたいです．リニアな型とか多層(?)な型とか型でできることとか．

**Comment by atton** [comment]
とりあえずコメント返しから。返答省いてるのはokですって意味合いでー。

> > 「関数型」の定義ってどこ参考にしてます?
> 
> 「1.「何であるか」をコンピュータに伝える」 は別に関数型の特徴とかでは無いし(純粋関数型の特徴？)，「2.高階関数」じゃなくて第一級関数が正しいですね．

アバウトには関数が第一級であるのが定義になると思う。
ちなみに私のソースは[関数プログラミング実践入門](http://gihyo.jp/book/2014/978-4-7741-6926-2)かな。読んではいないけれど。

> > 「実行すると必ず同じ結果を得られる」だと誤解を招きそうなレベルですごいように聞こえないかな。条件とか制約とか言いたいよね。どういう時に何が同じ結果?
> 
> ちょっとここ答えられないです…「再代入できる変数が無い」という制約の元で「同じ引数を与えれば返り値が必ず同じ結果」になる，で合ってますでしょうか…．
> すごいように聞こえると言えばIOな処理も実は〜みたいに紹介するべきですかね．

んー。その辺りは結構面倒な話で
関数レベルでの等価性は「引数が同じならば結果が同じ」
プログラムレベルでの等価性は「RealWorld が同じであれば結果が同じ」とかって話がある[みたい](https://www.haskell.org/haskellwiki/IO_inside)。
つまりIO Action の対象も引数として扱う、みたいな。
今回は「関数の参照等価性」くらいで良いんじゃないかな

> > リストの説明で「同じ要素の集まり」って [1,1,1,1] とかに誤解されないかな
> > タプル「違う種類もok」種類とかって型をぼかして言う方が良いのかな。型って言うとまずい?
> 
> あえて型って言うのを避けて要素とか種類とか書いてました．「型とはなんぞや」みたいな話になってしまいそうで…

なら止めないかなー。マエケンさんの説明に任せます

> > 「型は必ず大文字から」の後にTrueあるの大丈夫かな。あれってなして大文字なのかとかね。
> 
> 正確には「型と値コンストラクタ」が大文字ですね…値コンストラクタだとあれなので「型が取りうる値の種類」とかですかね．

okok 。説明できればokかな。
「型が取りうる値」はどう構成されるかとか説明できるとなお良いかも。

**Comment by atton** [comment]
24日了解です。 じゃあ Proofs and Types ですかねー

**Comment by kazuminn** [comment]
24日の勉強スタイルは、どんな感じですかー？

**Comment by maeken2010** [comment]
予定ではゼミ室でがしがしやりたいと思ってます．
正確な時間はまだ未定ですが午後の2時頃，とかですかね．

**Comment by maeken2010** [comment]
ひとまず勉強会お疲れ様でした！
attonさんお世話になりました．ありがとうございました．

**Comment by innparusu** [comment]
お疲れ様でした！

**Comment by atton** [comment]
大分連絡遅くなりましたがお疲れさまです。

ログ的に24日は Proofs and Types を Curry Howard Isomorphism まで(P15くらい?)まで読みました
基本的に目次の項目を全体的に流してあとは読む。
問題はソフトウェア工学のページのやつを参考にしたり。
だいたい3時間くらい? 型にまつわる話の目次をざらっと読むのが1時間くらいであとはずっと読んでた、かな
