### ISSUE TITLE
mainオブジェクト

### ISSUE THREAD

**Issue by kazuminn** [ie-developers/ie-questions#8]
mainオブジェクトって

main = Object.new
的な感じでインスタンス化されているのですか？

**Comment by hanachin** [comment]
はい。Rubyが起動するときに裏でインスタンス化されています。
具体的にはこのあたり https://github.com/ruby/ruby/blob/v2_1_5/vm.c#L2836,L2838

**Comment by hanachin** [comment]
MRIだとCレベルで[rb_obj_alloc](http://rurema.clear-code.com/2.1.0/function/rb_obj_alloc.html)という関数を使ってクラスをインスタンス化しています。

**Comment by hanachin** [comment]
Rubiniusとかだと多分このあたり、でもやってることはいっしょ。
https://github.com/rubinius/rubinius/blob/f846083a15165880ee01b33acdd5bb2ad49887fc/vm/ontology.cpp#L404,L405

**Comment by hanachin** [comment]
JRubyだとこのあたりかな
https://github.com/jruby/jruby/blob/d7cf4962ea47095d28252523fc6d8fd726ebe3c1/core/src/main/java/org/jruby/truffle/runtime/core/CoreLibrary.java#L268

**Comment by hanachin** [comment]
mrubyだとたぶんこのへん
https://github.com/mruby/mruby/blob/15b9771abc985028ec7910726f058e975504a1f0/src/state.c#L276

**Comment by kazuminn** [comment]
おー。！たくさんありがとうございますーー。
cのコード読んでみます。
