### ISSUE TITLE
gem therubyracerが入らないです。

### ISSUE THREAD

**Issue by kazuminn** [ie-developers/ie-questions#9]
centos7
ruby 2.1.5 
rails 4.1.8

で下記を実行すると怒られます。
原因がわかりません。

[ie-user@localhost SRU]$ gem install therubyracer
Building native extensions.  This could take a while...
ERROR:  Error installing therubyracer:
    ERROR: Failed to build gem native extension.

```
/home/ie-user/.rbenv/versions/2.1.5/bin/ruby extconf.rb
```

checking for main() in -lpthread... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling accessor.cc
make: g++: コマンドが見つかりませんでした
make: **\* [accessor.o] エラー 127

make failed, exit code 2

Gem files will remain installed in /home/ie-user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/therubyracer-0.12.1 for inspection.
Results logged to /home/ie-user/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/therubyracer-0.12.1/gem_make.out

**Comment by hanachin** [comment]
エラーメッセージの

> make: g++: コマンドが見つかりませんでした

の内容ままでg++コマンドがインストールされてないのかな?

エラーメッセージの読み方覚えるとデバッグ捗ります。

**Comment by kazuminn** [comment]
あ、できました。ありがとうございます。

エラーメッセージの読み方覚えます。
